{{- if and $.Values.certManager.enabled $.Values.certManager.defaultClusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
{{- if $.Values.certManager.defaultClusterIssuer.spec }}
  {{- tpl (toYaml $.Values.certManager.defaultClusterIssuer.spec) $ | nindent 2 }}
{{- else }}
  selfSigned: {}
{{- end }}
{{- end }}
